#!/bin/sh

# restart service
brew services restart docker-machine

# create driver
docker-machine create --driver virtualbox default

# set up env variable
eval $(docker-machine env default)

# login
# login=$(pass docker)
# sed '2q;d' <<< login | docker login -u "$(sed '2q;d')"
pass docker | xargs -n2 sh -c 'docker login -u "$1" --password-stdin <<< "$2"' sh
# pass docker | xargs -n2 sh -c 'docker login -u "$1" -p "$2"' sh
# pass docker | parallel -N 2 docker login -u={1} -p={2}
