#!/bin/sh

# Close any open System Preferences panes
osascript -e 'quit app "System Preferences"'

# configure osx and set dock elements
$XDG_CONFIG_HOME/osx/osx
$XDG_CONFIG_HOME/osx/dock

for app in "Activity Monitor" \
  "Dock" \
  "Finder" \
  "Messages" \
  "Safari" \
  "cfprefsd" \
  "SystemUIServer"; do
  killall "${app}" &> /dev/null
done

echo "OSX Config Complete."
echo "Some of these changes require a logout/restart to take effect."
