#!/bin/zsh

# Close any open System Preferences panes
osascript -e 'quit app "System Preferences"'

#===============================================================================
# GENERAL UI/UX
#===============================================================================

# Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# Always show scrollbars (Possible values: `WhenScrolling`, `Automatic` and `Always`)
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# initial key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# key repear
defaults write NSGlobalDomain KeyRepeat -int 1

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct (none, crashreport)
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Avoid creating .DS_Store files on network
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Avoid creating .DS_Store files on USB volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

#===============================================================================
# DOCK
#===============================================================================

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Enable highlight hover effect for the grid view of a stack (Dock)
defaults write com.apple.dock mouse-over-hilite-stack -bool true

# move dock orientation (options are left, bottom, right)
defaults write com.apple.dock orientation -string "bottom"

# Reset Launchpad
defaults write com.apple.dock ResetLaunchPad -bool true

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

# When switching to an application, switch to a space with open windows for the application
defaults write com.apple.dock workspaces-auto-swoosh -boolean YES

#===============================================================================
# FINDER
#===============================================================================

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool false

#===============================================================================
# MESSAGES
#===============================================================================

# Disable automatic emoji substitution (i.e. use plain text smileys)
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

# Disable smart quotes as it’s annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

#===============================================================================
# SAFARI
#===============================================================================

# Set Safari’s home page to `about:blank` for faster loading
defaults write com.apple.Safari HomePage -string "about:blank"

# Show Safari’s bookmarks bar by default
defaults write com.apple.Safari ShowFavoritesBar-v2 -bool true

# Hide Safari’s sidebar in Top Sites
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

# Enable the Develop menu in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true

# Enable the Web Inspector in Safari
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true

#===============================================================================
# SCREENSHOTS
#===============================================================================

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Save screenshots to the Pictures/Screenshots
defaults write com.apple.screencapture location -string "${XDG_DATA_HOME}/screenshots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

#===============================================================================
# KILL AFFECTED APPLICATIONS
#===============================================================================

for app in "Activity Monitor" \
  "Docker" \
  "Finder" \
  "Messages" \
  "Safari" \
	"cfprefsd" \
	"SystemUIServer"; do
	killall "${app}" &> /dev/null
done

echo "OSX Config Done."
echo "Some of these changes require a logout/restart to take effect."
