#!/bin/sh

killall dmenu-mac
rm -rf "/Applications/dmenu-mac.app"
# curl -s https://api.github.com/repos/oNaiPs/dmenu-mac/releases/latest \
#   | grep browser_download_url \
#   | cut -d ":" -f 2,3 \
#   | tr -d \" \
#   | wget --hsts-file="$XDG_CACHE_HOME/wget-hsts" -i -
wget --hsts-file="$XDG_CACHE_HOME/wget-hsts" \
  https://github.com/oNaiPs/dmenu-mac/releases/download/0.5.0/dmenu-mac.zip

unzip  "dmenu-mac.zip" -d "/Applications"
rm -rf "dmenu-mac.zip"
open "/Applications/dmenu-mac.app"
