#!/bin/zsh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

#===============================================================================
# HOMEBREW
#===============================================================================

# check for homebrew  mas, and install if missing
which brew &>/dev/null 2>&1 || (
  echo "Installing homebrew..." &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
)

which mas &>/dev/null 2>&1 || (
  echo "Installing mas..." &&
  brew install mas
)

# run installs/upgrades
# brew update
brew bundle -v
# brew cleanup
echo "Brew Setup Complete."

# quarantine homebrew gui apps
echo "Removing Apple Quarantine..."
HOMEBREW_NO_AUTO_UPDATE=1
brew cask list | xargs brew cask info | grep '(App)' \
  | sed 's/^/"\/Applications\//;s/\.app.*/.app"/' \
  | xargs sudo xattr -r -d com.apple.quarantine  &>/dev/null
HOMEBREW_NO_AUTO_UPDATE=0

#===============================================================================
# PIP
#===============================================================================

# check that pip3 is installed, install if missing
which pip3 &>/dev/null || (
  echo "Installing pip3..." &&
  brew install python # pip3 install -U pip
)

# install and upgrade existing packages
pip3 install -r "$PACKAGES_FOLDER/requirements.txt" -U

# install packages
xargs pip3 install < "$PACKAGES_FOLDER/pip.txt"

echo "Pip Setup Complete."
