#!/bin/sh

#===============================================================================
# YABAI SCRIPTING ADDON INSTALL
#===============================================================================

# install the scripting addition
sudo yabai --uninstall-sa
sudo yabai --install-sa

# load the scripting addition
killall Dock; brew services restart yabai
