#!/bin/zsh

# grab script directory and functions
DIR=$(realpath $(dirname $0))
source "$DIR/functions.sh"

function runDots() {
  # Ask for the administrator password upfront
  sudo -v

  # Keep-alive: update existing `sudo` time stamp until the script has finished
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

  # Run sections based on command line arguments
  for ARG in "$@"; do
    [ $ARG = "dots" ] || [ $ARG = "all" ] && dotfiles "$DIR"
    [ $ARG = "prep" ] || [ $ARG = "all" ] && os_prep
    [ $ARG = "pkg"  ] || [ $ARG = "all" ] && pkg_install
    [ $ARG = "pip"  ] || [ $ARG = "all" ] && pip_install
    [ $ARG = "git"  ] || [ $ARG = "all" ] && git_install
    [ $ARG = "os"   ] || [ $ARG = "all" ] && os_config
    [ $ARG = "xdg"  ] || [ $ARG = "all" ] && xdg_link
    [ $ARG = "wm"   ] || [ $ARG = "all" ] && wm_config
    # [ $ARG = "matlab"   ] || [ $ARG = "all" ] && matlab_install
    # [ $ARG = "wolfram"  ] || [ $ARG = "all" ] && mathematica_install
  done
  bigprint "Completed running dots. Please resart your computer."
  echo "Some of these changes require a logout/restart to take effect.\n"
}

read REPLY\?"This may overwrite existing files in ~/. Are you sure? (y/n): ";
if [[ $REPLY =~ ^[Yy]$ ]]; then
  runDots "$@"
fi;
unset runDots;
