#!/bin/zsh

DIR=$(realpath $(dirname $0))

function bootstrap() {

  # bootstrap scripts and configs
  URL="https://github.com/onesmallskipforman/bootstrap.git"
  git clone --recurse-submodules "$URL" "$DIR" || \
    git -C "$DIR" pull origin master && \
    git -C "$DIR" submodule foreach --recursive git pull origin master

  # remove old files, then symlink (or copy)
  rm -rf "$HOME"/{.config,.local,.zshenv}
  ln -sf "$DIR/Home"/{.config,.local,.zshenv} "$HOME"
  # cp -r "$DIR/Home"/{.config,.local,.zshenv} "$HOME"
}

if [[ "$1" == "--force" ]] || [[ "$1" == "-f" ]]; then
  doIt;
else
  printf '%s ' "This may overwrite existing files in your home directory. Are you sure? (y/n)";
  read REPLY;

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    bootstrap;
  fi;
fi;
unset doIt;
