#!/bin/zsh

# grab script directory and functions
DIR=$(dirname $0)
source "$DIR/functions.sh"

function runDots() {

  # Ask for the administrator password upfront
  sudo -v

  # Keep-alive: update existing `sudo` time stamp until the script has finished
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

  # Run sections based on command line arguments
  for ARG in "$@"; do
    [ $ARG = "bootstrap"   ] || [ $ARG = "all" ] && \
      bigprint "Syncing the dotfiles repo to home" && \
      $DIR/bootstrap -f
    [ $ARG = "osxprep"     ] || [ $ARG = "all" ] && osxprep
    [ $ARG = "homebrew"    ] || [ $ARG = "all" ] && homebrew_install
    [ $ARG = "termpdf"     ] || [ $ARG = "all" ] && termpdf_install
    [ $ARG = "refind"      ] || [ $ARG = "all" ] && refind_install
    [ $ARG = "config"      ] || [ $ARG = "all" ] && config
  done
  bigprint "Completed running dots. Please resart your computer."
  echo "Some of these changes require a logout/restart to take effect.\n"
}

# read -p "This may overwrite existing files in your home DIRectory. Are you sure? (y/n) " -n 1;
# echo "";
printf '%s ' "This may overwrite existing files in ~/. Are you sure? (y/n)";
read REPLY;

if [[ $REPLY =~ ^[Yy]$ ]]; then
    runDots "$@"
fi;

unset runDots;
