#!/bin/bash

source config_funcs.sh

quar "AppCleaner" 
quar "AppCode" 
quar "Arduino" 
quar "BetterSnapTool" 
quar "BetterTouchTool" 
quar "Bitwarden" 
quar "CLion" 
quar "CleanMyMac X" 
quar "CoolTerm" 
quar "Docker" 
quar "Dropbox" 
quar "Firefox" 
quar "Flux" 
quar "IntelliJ IDEA" 
quar "KeyboardCleanTool" 
quar "Minecraft" 
quar "NordVPN" 
quar "OpenEmu" 
quar "Paintbrush" 
quar "Porting Kit" 
quar "Protonmail Bridge" 
quar "PyCharm" 
quar "Skim" 
quar "Slack" 
quar "Spotify Notifications" 
quar "Spotify" 
quar "Steam" 
quar "Sublime Merge" 
quar "Sublime Text" 
quar "Thunderbird" 
quar "TickTick" 
quar "Tor Browser" 
quar "UI Browser" 
quar "Visual Studio Code" 
quar "XCTU" 
quar "XQuartz" "/Applications/Utilities"
quar "balenaEtcher" 
quar "iTerm" 
