#!/bin/zsh
set -euxo pipefail # https://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error

readonly ID=${1:-$(. /etc/os-release && echo $ID)}
case "$ID" in
  arch)   IMG=archlinux:base;;
  ubuntu) IMG=ubuntu:24.04;;
  *)      echo "Not a valid OS"; exit 1;;
esac

docker build --build-arg BASE=$IMG --build-arg OS=$1 -t dfile -f dockerfile .
docker run --rm -it dfile
