#!/bin/zsh
set -euxo pipefail # https://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error

function get_function_contents() {
  local FUNCTION=$1
  local FILE=$2
  pcregrep -M "(?s)function $FUNCTION.*?^}" $FILE \
    | sed '1d;$d;s/^  //g'
}

function header() {
  echo '
    #!/bin/bash
    set -euxo pipefail
  ' | awk '{$1=$1;print}' \
    | sed -e '/./,$!d'
}

function source_library() {
  echo '
    DIR=$(dirname $0 | xargs dirname | xargs realpath)
    source $DIR/library.sh
  ' | awk '{$1=$1;print}' \
    | sed -e '/./,$!d'
}

# function generate_file_contents() {
#   local FUNCTION=$1
#   local OS=$2
#   local OUT=$OS/$(echo $FUNCTION | sed 's/[A-Z]/-\L&/g')
#
#   header > $OUT
#   get_function_contents getSudo $OS.sh >> $OUT
# }

function cache_all() {
  local OS=$1
  header > $OS/get-sudo
  get_function_contents getSudo $OS.sh >> $OS/get-sudo
  chmod +x $OS/get-sudo

  header > $OS/prep
  source_library >> $OS/prep
  get_function_contents prep $OS.sh >> $OS/prep
  chmod +x $OS/prep

  header > $OS/packages
  source_library >> $OS/packages
  get_function_contents packages $OS.sh >> $OS/packages
  chmod +x $OS/packages
}

readonly ID=${1:-$(. /etc/os-release && echo $ID)}
case "$ID" in
  arch)   IMG=archlinux:base;;
  ubuntu) IMG=ubuntu:24.04;;
  *)      echo "Not a valid OS"; exit 1;;
esac

mkdir -p $1
cache_all $1

podman build --format docker --build-arg BASE=$IMG --build-arg OS=$1 -t dfile -f Containerfile .
podman run --rm -it dfile
