#!/bin/sh

#===================================================================
# MINECRAFT XDG TO OSX LINKING
#===================================================================

# Folders
XDG_CONFIG="$XDG_CONFIG_HOME/minecraft"
XDG_DATA="$XDG_DATA_HOME/minecraft"
OSX="$HOME/Library/Application Support/Minecraft"

# prep directories
rm    -rf "$OSX"/{launcher_profiles.json,options.txt,backups,saves}
mkdir -p  "$OSX"

# link
ln -sf "$XDG_CONFIG"/* "$OSX"
ln -sf "$XDG_DATA"/*   "$OSX"
