" keeps vim files in .config
" set runtimepath+=~/.config/vim,~/.config/vim/after
" set viminfo+=n~/.config/vim/viminfo

" different option for ordering
" let rtp=&runtimepath
" set runtimepath=~/.config/vim
" let &runtimepath.=','.rtp.',~/.config/vim/after'

set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set number
set backspace=indent,eol,start
