#!/bin/zsh

#===============================================================================
# OSX/COMMANDLINETOOLS UPDATE
#===============================================================================

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ensure zsh is the default shell
sudo chsh -s /bin/zsh

# Update OS
sudo softwareupdate -i -a -R --verbose # use sudo -s if you want -R option

# allows apps downloaded from anywhere
sudo spctl --master-disable

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "SkippersMBP"
sudo scutil --set HostName "SkippersMBP"
sudo scutil --set LocalHostName "SkippersMBP"
dscacheutil -flushcache
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "SkippersMBP"

# make screenshots directory
# mkdir -p "${XDG_DATA_HOME}/screenshots"

# Turn Dark mode on
osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'

# Set a custom wallpaper image
WALLPAPER="$XDG_DATA_HOME/wallpapers/beams.jpeg"
osascript -e "tell application \"Finder\" to set desktop picture to \"$(realpath "$WALLPAPER")\" as POSIX file"
osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"$(realpath "$WALLPAPER")\""

# Disable local Time Machine snapshots
sudo tmutil disable

# set up gpg permissions
find $GNUPGHOME -type f -exec chmod 600 {} \;
find $GNUPGHOME -type d -exec chmod 700 {} \;

# clean ~/
rm -rf "$HOME/.zsh_history"
rm -rf "$HOME/.DS_Store"

# install command line tools
xcode-select -p &>/dev/null 2>&1 || (
  echo "Installing Command Line Tools..." &&
  xcode-select --install
)
